### ISSUE TITLE
How do you use the code generated by this?

### ISSUE THREAD

**Issue by AwesomeKalin** [Zylann/godot_scene_code_converter#1]
Title

**Comment by Zylann** [comment]
This plugin is intented for C++ developers working on the Godot Editor itself (i.e this is not for GDNative users)

When you work on Godot's source code, it is common to need to create a user interface. However in this case it's not possible to just "load a scene file", since the Godot Editor itself comes as a single executable and nothing else. So instead (and probably for speed and dynamic stuff reasons), all interfaces are created by code. See for example the editor for AnimationPlayer: https://github.com/godotengine/godot/blob/d3ff3dc6ce96ef1d9d513917ff61abe62e266c19/editor/plugins/animation_player_editor_plugin.cpp#L1511

This can be tedious to write so I made this plugin, to allow prototyping interfaces with a scene, and then convert it into code.
This code can then be pasted in the place you want it to run in the Godot source code. Typically, it's placed in the constructor of the UI class representing the interface.

**Comment by AwesomeKalin** [comment]
Thanks!
